version: '3'

services:
  api:
    build: .
    volumes:
      - "./backend:/app"
    ports:
      - "3000:3000"
    depends_on:
      - db

  client:
      build: .
      volumes:
        - "./client:/app"
      ports:
        - "3030:3030"
      depends_on:
        - api

  db:
    image: 'bitnami/mongodb:latest'
    ports:
      - "27017:27017"
    environment:
      - MONGODB_USERNAME=test
      - MONGODB_PASSWORD=test1234
      - MONGODB_DATABASE=users
    volumes:
      - ./docker/db/data:/bitnami




